In [ ]:
import import_ipynb               # activate the hook
import beginning                  # NOT “beginning.ipynb”

In [14]:
%run -i ./beginning.ipynb

C:\Users\girth\AppData\Local\Temp\ipykernel_20156\2085239294.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

C:\Users\girth\AppData\Local\Temp\ipykernel_20156\2085239294.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

C:\Users\girth\AppData\Local\Temp\ipykernel_20156\2085239294.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\girth\AppData\Local\Temp\ipykernel_20156\2085239294.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

C:\Users\girth\AppData\Local\Temp\ipykernel_20156\2085239294.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rk,Player,Tm,2020-21,2021-22,2022-23,2023-24,2024-25,2025-26,BIRD,Guaranteed,Salary Count,Average Salary
0,1,Stephen Curry,GSW,"$45,780,966","$48,070,014","$51,915,615","$55,761,216","$59,606,817",NaN,Bird Rights,261134628.0,5,52226925.6
1,2,John Wall,HOU,"$44,310,840","$47,366,760",NaN,NaN,NaN,NaN,Bird Rights,44310840.0,2,22155420.0
2,3,Russell Westbrook,LAL,"$44,211,146","$47,063,478",NaN,NaN,NaN,NaN,Bird Rights,44211146.0,2,22105573.0
3,4,James Harden,BRK,"$43,848,000","$46,872,000",NaN,NaN,NaN,NaN,Bird Rights,43848000.0,2,21924000.0
4,5,LeBron James,LAL,"$41,180,544","$44,474,988",NaN,NaN,NaN,NaN,Bird,85655532.0,2,42827766.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,529,Emanuel Terry,PHO,"$85,578",NaN,NaN,NaN,NaN,NaN,Minimum Salary,85578.0,1,85578.0
581,530,Tyrell Terry,MEM,"$1,517,981","$1,782,621",NaN,NaN,NaN,NaN,NaN,85578.0,2,42789.0
582,531,Admiral Schofield,ORL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169706.0,0,inf
583,532,Malcolm Hill,CHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53176.0,0,inf
584,533,Malcolm Hill,ATL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53176.0,0,inf

,Rk,Player,Tm,2021-22,2022-23,2023-24,2024-25,2025-26,2026-27,BIRD,Guaranteed,Salary Count,Average Salary
0,1,Stephen Curry,GSW,"$45,780,966","$48,070,014","$51,915,615","$55,761,216","$59,606,817",NaN,Bird Rights,261134628.0,5,52226925.6
1,2,John Wall,HOU,"$44,310,840","$47,366,760",NaN,NaN,NaN,NaN,Bird Rights,44310840.0,2,22155420.0
2,3,Russell Westbrook,LAL,"$44,211,146","$47,063,478",NaN,NaN,NaN,NaN,Bird Rights,44211146.0,2,22105573.0
3,4,James Harden,BRK,"$43,848,000","$46,872,000",NaN,NaN,NaN,NaN,Bird Rights,43848000.0,2,21924000.0
4,5,LeBron James,LAL,"$41,180,544","$44,474,988",NaN,NaN,NaN,NaN,Bird,85655532.0,2,42827766.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,529,Emanuel Terry,PHO,"$85,578",NaN,NaN,NaN,NaN,NaN,Minimum Salary,85578.0,1,85578.0
581,530,Tyrell Terry,MEM,"$1,517,981","$1,782,621",NaN,NaN,NaN,NaN,NaN,85578.0,2,42789.0
582,531,Admiral Schofield,ORL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169706.0,0,inf
583,532,Malcolm Hill,CHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53176.0,0,inf
584,533,Malcolm Hill,ATL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53176.0,0,inf

,Rk,Player,Tm,2022-23,2023-24,2024-25,2025-26,2026-27,2027-28,Guaranteed,Salary Count,Average Salary
0,1,Stephen Curry,GSW,"$48,070,014","$51,915,615","$55,761,216","$59,606,817",NaN,NaN,215353662,4,5.383842e+07
1,2,Russell Westbrook,UTA,"$47,559,433",NaN,NaN,NaN,NaN,NaN,47063478,1,4.706348e+07
2,3,LeBron James,LAL,"$44,474,988","$53,369,986","$57,639,585",NaN,NaN,NaN,97844974,3,3.261499e+07
3,4,Kevin Durant,PHO,"$44,119,845","$47,649,433","$51,179,021","$54,708,609",NaN,NaN,197656908,4,4.941423e+07
4,5,Bradley Beal,WAS,"$43,279,250","$46,741,590","$50,203,930","$53,666,270","$57,128,610",NaN,193891040,5,3.877821e+07
...,...,...,...,...,...,...,...,...,...,...,...,...
617,562,Charles Bassey,PHI,"$2,674,742","$2,600,000","$2,500,000","$2,500,000",NaN,NaN,74742,4,1.868550e+04
618,563,Trevor Keels,NYK,NaN,NaN,NaN,NaN,NaN,NaN,58493,0,inf
619,564,Lester Quinones,GSW,NaN,NaN,NaN,NaN,NaN,NaN,58493,0,inf
620,565,Stanley Umude,DET,"$58,493",NaN,NaN,NaN,NaN,NaN,58493,1,5.849300e+04
621,566,Saben Lee,TOR,"$1,752,638",NaN,NaN,NaN,NaN,NaN,10492,1,1.049200e+04

,Rk,Player,Tm,2023-24,2024-25,2025-26,2026-27,2027-28,2028-29,Guaranteed,Salary Count,Average Salary
0,1,Stephen Curry,GSW,"$51,915,615","$55,761,216","$59,606,817",NaN,NaN,NaN,167283648.0,3,55761216.0
1,2,Kevin Durant,PHO,"$47,649,433","$51,179,021","$54,708,609",NaN,NaN,NaN,153537063.0,3,51179021.0
2,3,Nikola Jokić,DEN,"$47,607,350","$51,415,938","$55,224,526","$59,033,114","$62,841,702",NaN,213280928.0,5,42656185.6
3,4,Joel Embiid,PHI,"$47,607,350","$51,415,938","$55,224,526","$59,033,114",NaN,NaN,154247814.0,4,38561953.5
4,5,LeBron James,LAL,"$47,607,350","$51,415,938",NaN,NaN,NaN,NaN,47607350.0,2,23803675.0
...,...,...,...,...,...,...,...,...,...,...,...,...
611,558,Matthew Hurt,MEM,NaN,NaN,NaN,NaN,NaN,NaN,64343.0,0,inf
612,559,Pete Nance,CLE,"$64,343",NaN,NaN,NaN,NaN,NaN,64343.0,1,64343.0
613,560,Malik Williams,TOR,"$77,212",NaN,NaN,NaN,NaN,NaN,77212.0,1,77212.0
616,561,Kai Jones,LAC,"$3,175,563","$2,196,970",NaN,NaN,NaN,NaN,11608.0,2,5804.0
617,562,Usman Garuba,GSW,"$2,600,008",NaN,NaN,NaN,NaN,NaN,11608.0,1,11608.0

,Rk,Player,Tm,2024-25,2025-26,2026-27,2027-28,2028-29,2029-30,Guaranteed,Salary Count,Average Salary
0,1,Stephen Curry,GSW,"$55,761,216","$59,606,817","$62,587,158",NaN,NaN,NaN,177955191,3,59318397.0
1,2,Joel Embiid,PHI,"$51,415,938","$55,224,526","$57,985,752","$62,624,612","$67,263,472",NaN,227250828,5,45450165.6
2,3,Nikola Jokić,DEN,"$51,415,938","$55,224,526","$59,033,114","$62,841,702",NaN,NaN,165673578,4,41418394.5
3,4,Kevin Durant,PHO,"$51,179,021","$54,708,609",NaN,NaN,NaN,NaN,105887630,2,52943815.0
4,5,Bradley Beal,PHO,"$50,203,930","$53,666,270","$57,128,610",NaN,NaN,NaN,103870200,3,34623400.0
...,...,...,...,...,...,...,...,...,...,...,...,...
539,492,Javon Freeman-Liberty,TOR,"$100,000",NaN,NaN,NaN,NaN,NaN,100000,1,100000.0
540,493,Erik Stevenson,WAS,"$66,503",NaN,NaN,NaN,NaN,NaN,66503,1,66503.0
541,494,Branden Carlson,OKC,"$496,519",NaN,NaN,NaN,NaN,NaN,496519,1,496519.0
542,495,Branden Carlson,OKC,"$496,519",NaN,NaN,NaN,NaN,NaN,496519,1,496519.0
543,496,Javante McCoy,DET,"$47,265",NaN,NaN,NaN,NaN,NaN,47265,1,47265.0

,Rk,Player,Tm,2023-24,2024-25,2025-26,2026-27,2027-28,2028-29,Guaranteed,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Player-additional
0,1,Stephen Curry,GSW,"$51,915,615","$55,761,216","$59,606,817",NaN,NaN,NaN,167283648.0,...,0.5,4.0,4.5,5.1,0.7,0.4,2.8,1.6,26.4,curryst01
1,2,Kevin Durant,PHO,"$47,649,433","$51,179,021","$54,708,609",NaN,NaN,NaN,153537063.0,...,0.5,6.1,6.6,5.0,0.9,1.2,3.3,1.8,27.1,duranke01
2,3,Nikola Jokić,DEN,"$47,607,350","$51,415,938","$55,224,526","$59,033,114","$62,841,702",NaN,213280928.0,...,2.8,9.5,12.4,9.0,1.4,0.9,3.0,2.5,26.4,jokicni01
3,4,Joel Embiid,PHI,"$47,607,350","$51,415,938","$55,224,526","$59,033,114",NaN,NaN,154247814.0,...,2.4,8.6,11.0,5.6,1.2,1.7,3.8,2.9,34.7,embiijo01
4,5,LeBron James,LAL,"$47,607,350","$51,415,938",NaN,NaN,NaN,NaN,47607350.0,...,0.9,6.4,7.3,8.3,1.3,0.5,3.5,1.1,25.7,jamesle01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,557,Trey Jemison,MEM,NaN,NaN,NaN,NaN,NaN,NaN,64343.0,...,2.6,2.8,5.4,1.1,0.5,1.1,1.4,2.8,6.8,jemistr01
526,558,Matthew Hurt,MEM,NaN,NaN,NaN,NaN,NaN,NaN,64343.0,...,1.1,0.9,2.0,0.5,0.4,0.4,0.3,1.0,4.0,hurtma01
527,559,Pete Nance,CLE,"$64,343",NaN,NaN,NaN,NaN,NaN,64343.0,...,0.0,0.4,0.4,0.0,0.1,0.0,0.1,0.3,0.4,nancepe01
528,560,Malik Williams,TOR,"$77,212",NaN,NaN,NaN,NaN,NaN,77212.0,...,2.1,3.3,5.4,0.3,0.4,0.6,0.4,2.1,2.7,willima11
529,562,Usman Garuba,GSW,"$2,600,008",NaN,NaN,NaN,NaN,NaN,11608.0,...,0.5,0.7,1.2,0.2,0.2,0.5,0.3,0.3,0.5,garubus01

In [16]:
import numpy as np
import pandas as pd
from sklearn.ensemble         import RandomForestRegressor
from sklearn.model_selection import GroupShuffleSplit
from sklearn.pipeline        import Pipeline
from sklearn.impute          import SimpleImputer
from sklearn.preprocessing   import StandardScaler
from sklearn.metrics         import mean_squared_error, r2_score

# —————————————————————————————————————————————————————————————
# 0) Assume `all_seasons` already exists as in your previous step
# —————————————————————————————————————————————————————————————
df = all_seasons.copy()
df = df[df['Average Percent of Cap'].notna()]

feature_cols = [
    'Games', 'Games Started', 'MP',
    'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
    '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
    'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV',
    'PF', 'PTS'
]

X = df[feature_cols]
y = df['Average Percent of Cap']
groups = df['Player']

# —————————————————————————————————————————————————————————————
# 1) Group‑aware train/test split
# —————————————————————————————————————————————————————————————
gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# (optional) check no overlap
assert set(df['Player'].iloc[train_idx]).isdisjoint(df['Player'].iloc[test_idx])

# —————————————————————————————————————————————————————————————
# 2) Build & train the pipeline
# —————————————————————————————————————————————————————————————
pipe = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale',   StandardScaler()),
    ('rf',      RandomForestRegressor(
                   n_estimators=200,
                   max_depth=8,
                   random_state=42,
                   n_jobs=-1))
])

pipe.fit(X_train, y_train)

# —————————————————————————————————————————————————————————————
# 3) Evaluate on the test set
# —————————————————————————————————————————————————————————————
y_pred = pipe.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print(f"Test  RMSE: {rmse:.4f}")
print(f"Test  R²:   {r2:.4f}")

# (optional) inspect a few predictions
results = pd.DataFrame({
    'Player':    df['Player'].iloc[test_idx].values,
    'Season':    df['Season'].iloc[test_idx].values,
    'Actual':    y_test.values,
    'Predicted': y_pred
    #'Difference': y_test.values - y_pred
})

NameError: name 'all_seasons' is not defined

In [ ]:
# 1) Define your cap numbers (fill in with the official NBA caps)
cap_by_season = {
    '2020-21': 10914000000 ,   # $109.14 M
    '2021-22': 112414000000,   # $112.41 M
    '2022-23': 12365500000,   # $121.25 M
    '2023-24': 13602100000,   # $136.61 M
    '2024-25': 14058800000    # $154.74 M (projected)
}

# 2) Map cap into your results
results['Cap'] = results['Season'].map(cap_by_season)

# 3) Compute actual salaries
#    if your % columns are literal percentages (e.g. 35.7 for 35.7%), divide by 100:
results['Actual Salary']    = results['Actual']    / 100 * results['Cap']
results['Predicted Salary'] = results['Predicted'] / 100 * results['Cap']

# 4) (Optional) round to nearest dollar, reorder columns
results = results[[
    'Player','Season',
    'Actual','Actual Salary',
    'Predicted','Predicted Salary'
]].assign(
    **{
      'Actual Salary':    lambda df: df['Actual Salary'].round(0).astype(int),
      'Predicted Salary': lambda df: df['Predicted Salary'].round(0).astype(int),
    }
)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble         import RandomForestRegressor
from sklearn.model_selection import GroupShuffleSplit
from sklearn.pipeline        import Pipeline
from sklearn.impute          import SimpleImputer
from sklearn.preprocessing   import StandardScaler
from sklearn.metrics         import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# —————————————————————————————————————————————————————————————
# 0) Start from all_seasons
# —————————————————————————————————————————————————————————————
df2 = all_seasons.copy()

# —————————————————————————————————————————————————————————————
# 1) Drop missing / non‑positive salaries
# —————————————————————————————————————————————————————————————
df2 = df2[df2['Average Salary'].notna() & (df2['Average Salary'] > 0)]

# —————————————————————————————————————————————————————————————
# 2) Define X, y (Series), groups
# —————————————————————————————————————————————————————————————
feature_cols = [
    'Games','Games Started','MP',
    'FG','FGA','FG%','3P','3PA','3P%',
    '2P','2PA','2P%','eFG%','FT','FTA','FT%',
    'ORB','DRB','TRB','AST','STL','BLK','TOV',
    'PF','PTS'
]
X      = df2[feature_cols]
y      = df2['Average Salary']       # pandas Series
groups = df2['Player']

# —————————————————————————————————————————————————————————————
# 3) Compute log and drop any remaining infinities
# —————————————————————————————————————————————————————————————
y_log = np.log(y)
mask  = np.isfinite(y_log)
X      = X[mask]
y      = y[mask]
y_log  = y_log[mask]
groups = groups[mask]
df2    = df2[mask]                    # keep in sync

# —————————————————————————————————————————————————————————————
# 4) Group‑aware train/test split
# —————————————————————————————————————————————————————————————
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y_log, groups=groups))

X_train, X_test   = X.iloc[train_idx],    X.iloc[test_idx]
y_train_log       = y_log.iloc[train_idx]
y_test            = y.iloc[test_idx]      # real dollars

# —————————————————————————————————————————————————————————————
# 5) Build & fit pipeline on log‑target
# —————————————————————————————————————————————————————————————
pipe = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale',   StandardScaler()),
    ('rf',      RandomForestRegressor(
                    n_estimators=200,
                    max_depth=8,
                    random_state=42,
                    n_jobs=-1))
])
pipe.fit(X_train, y_train_log)

# —————————————————————————————————————————————————————————————
# 6) Predict & back‑transform
# —————————————————————————————————————————————————————————————
y_pred_log = pipe.predict(X_test)
y_pred     = np.exp(y_pred_log)

# —————————————————————————————————————————————————————————————
# 7) Evaluate on original scale
# —————————————————————————————————————————————————————————————
#rmse = mean_squared_error(y_test, y_pred, squared=False)
r2   = r2_score(y_test, y_pred)
print(f"Test  RMSE (dollars): ${rmse:,.0f}")
print(f"Test  R²:            {r2:.4f}")

# —————————————————————————————————————————————————————————————
# 8) Results table & plot
# —————————————————————————————————————————————————————————————
results = pd.DataFrame({
    'Player':      df2['Player'].iloc[test_idx].values,
    'Season':      df2['Season'].iloc[test_idx].values,
    'Actual $':    y_test.values,
    'Predicted $': y_pred
})

print(results.head())

plt.figure()
plt.scatter(results['Actual $'], results['Predicted $'], alpha=0.7)
lims = [
    min(results['Actual $'].min(), results['Predicted $'].min()),
    max(results['Actual $'].max(), results['Predicted $'].max())
]
plt.plot(lims, lims, 'k--', linewidth=1)
plt.xlabel('Actual Salary')
plt.ylabel('Predicted Salary')
plt.title('Predicted vs Actual Salary (log‐trained model)')
plt.show()

In [ ]:
plt.figure()
plt.scatter(
    all_seasons.index, 
    all_seasons['Average Percent of Cap'],
    alpha=0.7
)
plt.xlabel('Player Index')
plt.ylabel('Average Percent of Cap')
plt.title('Scatter of Average Percent of Cap Across Players')
plt.show()